### ISSUE TITLE
CUDNN cache locking prevents finalizers resulting in OOMs

### ISSUE THREAD

**Issue by mashu** [JuliaGPU/CUDA.jl#1461]
**Describe the bug**

Have been working on model using 5 CNN layers and Dense, but same model that worked before after updating CUDA started giving out error

```
Out of GPU memory trying to allocate 653.794 MiB
Effective GPU memory usage: 99.32% (7.734 GiB/7.787 GiB)
Memory pool usage: 5.630 GiB (6.344 GiB reserved)
```
Revetring back to CUDA@3.8.0 which I luckily had in git log fixed the problem.

**To reproduce**

I used https://github.com/FluxML/model-zoo/tree/master/vision/conv_mnist
Updated CUDA and Flux to latest versions and changed a bit model to make it stupidly bigger so number of parameters is more similar to my model. See attached diff
[LaNet.txt](https://github.com/JuliaGPU/CUDA.jl/files/8411050/LaNet.txt)

<details><summary>Manifest.toml</summary>
<p>

I've tested in the following order
```
 CUDA@3.8.5 #1 memory out
 CUDA@3.8.4 #2 memory out #6 memory out again
 CUDA@3.8.0 #3 works
 CUDA@3.8.2 #4 works
 CUDA@3.8.3 #5 works
```
So something bad happens between 3.8.3 and 3.8.4.

</p>
</details>

**Expected behavior**

I expected the same code that worked before to still work with CUDA@3.8.4+

**Version info**

Details on Julia:

```
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 6
  JULIA_EDITOR = atom  -a
```

Details on CUDA:

```
CUDA toolkit 11.6, artifact installation
NVIDIA driver 470.103.1, for CUDA 11.4
CUDA driver 11.4

Libraries: 
- CUBLAS: 11.8.1
- CURAND: 10.2.9
- CUFFT: 10.7.0
- CUSOLVER: 11.3.2
- CUSPARSE: 11.7.1
- CUPTI: 16.0.0
- NVML: 11.0.0+470.103.1
- CUDNN: 8.30.2 (for CUDA 11.5.0)
  Downloaded artifact: CUTENSOR
- CUTENSOR: 1.4.0 (for CUDA 11.5.0)

Toolchain:
- Julia: 1.7.2
- LLVM: 12.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: NVIDIA GeForce RTX 2070 with Max-Q Design (sm_75, 4.775 GiB / 7.787 GiB available)
```

**Additional context**

With broken CUDA@3.8.4 using 
```
    GC.gc(true);
    CUDA.reclaim();
```
at the end of each mini-batch also helped to keep memory usage down to 21%, when this is not done in all cases nvtop shows 100% memory usage, but CUDA 3.8.0->3.8.3 is not crashing with out of memory error, while 3.8.4 and 3.8.5 just crash.

**Comment by maleadt** [comment]
Since it works on 3.8 and not on 3.8.4, between which there shouldn't have been any significant changes, could you try bisecting to see where the issue was introduced?

**Comment by fabricerosay** [comment]
If this can help, it seems related  https://discourse.julialang.org/t/oom-when-using-flux-and-loops/79468/5?u=fabrice_rosay

**Comment by ToucheSir** [comment]
That issue may be in part due to invalidation of the cuDNN [conv algorithm descriptor cache](https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cudnn/convolution.jl#L172-L187) in CUDA.jl. Note how said cache is keyed by input, so if the input size changes then a somewhat compute + memory-intensive algorithm search will have to happen again. It seems to me that the constraints on this cache could probably be loosened (e.g. use input size + eltype + strides instead of a descriptor, ignore the batch dimension, etc) but unsure of any potential negative side effects.

**Comment by fabricerosay** [comment]
I don't know enough about CUDNN but I made the change in my algo( a kind of alphazero) to use a constant batch size and the gpu usage went much higher from between 20 to 40  and a strange behaviour where sometimes it dropped under 1% to above 70% and steady, which largely compensate the fact that you do useless computation... This also could be related with the addition of lock in cudnn to make it compatible with threading, which happened in  3.8.4, making this behaviour even more pronouced. (sorry for the English:). As another hint pointing to this direction, when i enable multithreading, i encounter a lot of dead lock: sometimes it runs smoothly for hours and sometimes it won't even start.

**Comment by ToucheSir** [comment]
Yeah, in that case I'd be pretty confident it is the repeated algorithm selection that is the culprit (the lock creates basically no overhead, IIUC). You can confirm this by running an nsight profile (see the docs for this package on how to do that) and checking the CUDA API calls. If there are repeated blocks of kernels with names containing "fft", "conv", "winograd" etc for each new input size, then that's indicative of algorithm selection. If instead you only see such a block at the beginning and somewhat regular calls to routines with "conv" in the name afterwards, then no re-tuning is happening.

**Comment by fabricerosay** [comment]
I once tried to use nsight profile which ended in a major failure. But as I just got tested COVID positif I will have some time to try again:)
Between in my experiments only the batching dimension is changing, do you think it would be easy to force the same algo to be used ?

**Comment by ToucheSir** [comment]
Unfortunately not without modifying either CUDA or NNlib(CUDA) + Flux. There would need to be some mechanism for passing in `p` [here](https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cudnn/convolution.jl#L102) instead of unconditionally running an algorithm search (even if it hits the cache). I count ~4 layers of functions between there and Flux's `Conv` layer, so you'd either have to thread it through the call stack or come up with some non-local mechanism for relaying the option like how math mode is currently done. This would probably tie in with https://github.com/JuliaGPU/CUDA.jl/issues/938 as well.

**Comment by fabricerosay** [comment]
If I understand correctly, there's a whole machiney in Flux and nnlib to decide which algo to perform, but then it mostly call cudnn.
As most of the time is spent on inference in alphazero, I could make a small script that given a flux model call directly cuddn to perform the convolution, if needed using first the heavy machinery to find the best algorithm on average batch size and then switching back to flux for training. In most sessions the network have the same toppology.

Anyway training is very stable now.  We had this issue from the begining suspecting some leaks or gc, getting crazy... this could be very valuable for alphazero.jl, which suffer from the same problem.

I will try to go back to 3.9 and multithreading and see.

**Comment by ToucheSir** [comment]
> If I understand correctly, there's a whole machiney in Flux and nnlib to decide which algo to perform, but then it mostly call cudnn.

It's actually the opposite: the machinery exists only in CUDA.jl, so Flux and NNlib have no idea which algorithm is chosen. That's why it's hard to manually specify algorithm types, because the API boundary between the lowest-level Julia library and the next highest level provides no knobs to tune them.

**Comment by fabricerosay** [comment]
It works flawlessly with CUDA 3.9 and multithreading provided batch size is constant.

**Comment by tclements** [comment]
I just ran into a similar OOM problem when doing convolution on graph features with GraphNeuralNetworks.jl https://github.com/CarloLucibello/GraphNeuralNetworks.jl/issues/150. In my case, enforcing a constant batch size is tricky because the batch size is a function of the number of nodes in each graph, which varies graph to graph.

 Is there a way around having to do the conv algo search when batch size varies? All other input dimensions remain the same during training/inference.

**Comment by fabricerosay** [comment]
I tried to hack directly into cudnn, there you can force an algorithm.  For example i tried  CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM = 0 always and memory consumption dropped. . Problem is it seems some algorithm do not work for some convolutions and if you cancel the call to algo search you have to guess memmory consumption.
Hacking directly into cudnn you can print which algo is used so one very ugly workaround would be to force the googd algorithm at each step depending on the structure of your network. 
This would allow to bypass the optimization step. If speed is not an issue it could work.
You have to change p.algo there with something like  CUDA.CUDNN.cudnnConvolutionFwdAlgo_t(0)
https://github.com/JuliaGPU/CUDA.jl/blob/146ad00c0f7b328478d4b61c6f7919b2f8acd5c5/lib/cudnn/convolution.jl#L105

For me it worked dividing memory usage by 2. I don't know yet how it will perform on a longer run. I have to wait till tomorrow morning.
All in all it is very ugly

**Comment by tclements** [comment]
Thanks, that's really helpful! Probably a bit too low-level for what I'm trying to do with varying convolution sizes. 

@ToucheSir if there's a way to not trigger the algorithm search if only the batch size dimension varies, that would be awesome!

**Comment by ToucheSir** [comment]
@tclements per my comment at https://github.com/JuliaGPU/CUDA.jl/issues/1461#issuecomment-1099318455, someone would have to figure out the minimum subset of properties required to safely cache conv algorithms without relying on descriptor identity.

**Comment by fabricerosay** [comment]
It should be possible as there is a dict that keeps algo and memory usage found for different configuration encountered. Currently i think it keeps track of all dimensions, it would be enough to drop the batch size dimension. Only problem is that it also stores the memory needed to call cudnn, which most probably varies with batchsize, but it should be easier and faster to calculate than the whole search. It is also something at the level of cudnn. But frankly it is not so hard, didn't know about it one hour ago.  The code is very well documented.

**Comment by ToucheSir** [comment]
Yes, if it wasn't clear (and I think @maleadt would agree) this is a "PRs welcome" ;)

**Comment by maleadt** [comment]
I can't reproduce this, probably because my GPU has more memory though. In addition, the conv_mnist model-zoo example at some point due to BSON (using the included Manifest on Julia 1.7). So again, could anybody who is running into this please bisect this to the actual change?

**Comment by fabricerosay** [comment]
Here is a MWE. this code works till 3.8.3 and errors with OOM from 3.8.4


```julia
using CUDA
using Flux


function optimize(actor,n)

    for k in 1:n
        batch=rand(Float32,9,9,3,k)
        batch_gpu=batch|>gpu

        v_gpu=actor(batch_gpu)
        v=v_gpu|>cpu
  
    
        CUDA.unsafe_free!(batch_gpu)

        CUDA.unsafe_free!(v_gpu)
        
    end

end


actor=Chain(Conv((3,3),3=>128,pad=1,relu),[Chain(Conv((3,3),128=>128,pad=1,relu),BatchNorm(128)) for k in 1:20]...,Flux.flatten,Dense(81*128,81))|>gpu
optimize(actor,1000)
```

**Comment by maleadt** [comment]
> till 3.8.3 and errors with OOM from 3.8.4

There's two memory related commits in there, https://github.com/JuliaGPU/CUDA.jl/compare/v3.8.3...v3.8.4, could you check which commit exactly is the culprit? If it's the locking one, are you running with threads or not? And which Julia & CUDA versions specifically?

EDIT: I can reproduce with the above MWE using a single thread. The culprit is the locking change.

**Comment by maleadt** [comment]
I don't understand why the locking change causes this issue (it reproduces using a single thread, and the lock is always uncontended), but my hypothesis is that the dictionary containing algorithm selection results keeps the CUDNN handles alive, resulting in higher memory usage. Not easy to fix though, a WeakKeyDict doesn't work here (since we store a tuple of multiple descriptors), and I don't think we want to key on the descriptor properties either (because we then need to include all possible things CUDNN might be considering) -- even though it looks like this is what e.g. CNTK does https://github.com/microsoft/CNTK/pull/3362

**Comment by maleadt** [comment]
So the problem seems more fundamental: locked code runs with finalizers disabled, which results in the workspace allocation failing as soon as we run close to OOM (whereas it normally would try to reclaim memory by forcing finalizers to execute):

```
julia> inhibit_finalizers() = unsafe_load(convert(Ptr{Int32}, Core.getptls()+32 #=offset=#))
inhibit_finalizers (generic function with 1 method)

julia> @show inhibit_finalizers(); GC.disable_finalizers(); @show inhibit_finalizers(); GC.enable_finalizers(); @show inhibit_finalizers()
inhibit_finalizers() = 0
inhibit_finalizers() = 1
inhibit_finalizers() = 0
```

```
julia> lock(x) do
       inhibit_finalizers()
       end
1
```

This is because of how `trylock` is implemented: https://github.com/JuliaLang/julia/blob/6026b5ff2a8035fc9d70af30123af9a6e722c585/base/lock.jl#L124-L132=. It's a pretty fundamental restriction that I'll need to take into account for lots of code...

**Comment by fabricerosay** [comment]
Thanks for investigating. So as long as no cuddn calls are done in multiple threads, it is safe to remove the lock ?(in my application all evaluation are done by a server)

**Comment by maleadt** [comment]
It is, but we generally want CUDA.jl to be thread-safe so we'll need to find a solution around this. I could make the locks more fine-grained (i.e., only lock a `haskey` and `setindex` call), but that's somewhat error-prone and I'd like a better solution. If I don't find any, I'll push a hotfix.

**Comment by maleadt** [comment]
Actually, I pushed a hotfix already. Please test https://github.com/JuliaGPU/CUDA.jl/pull/1491

**Comment by fabricerosay** [comment]
I did add CUDA #master.
Still getting the same error related to lock and OOM:
(besides: 
CUDA toolkit 11.6, artifact installation
NVIDIA driver 510.47.3, for CUDA 11.6
CUDA driver 11.6

Libraries: 
- CUBLAS: 11.8.1
- CURAND: 10.2.9
- CUFFT: 10.7.0
- CUSOLVER: 11.3.2
- CUSPARSE: 11.7.1
- CUPTI: 16.0.0
- NVML: 11.0.0+510.47.3
- CUDNN: 8.30.2 (for CUDA 11.5.0)
- CUTENSOR: 1.4.0 (for CUDA 11.5.0)

Toolchain:
- Julia: 1.7.2
- LLVM: 12.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: NVIDIA GeForce RTX 3080 (sm_86, 8.184 GiB / 10.000 GiB available))
```julia
ERROR: LoadError: Out of GPU memory trying to allocate 324.316 MiB
Effective GPU memory usage: 99.94% (9.775 GiB/9.780 GiB)
Memory pool usage: 7.975 GiB (8.250 GiB reserved)
Stacktrace:
  [1] macro expansion
    @ ~/.julia/packages/CUDA/QjuNX/src/pool.jl:311 [inlined]
  [2] macro expansion
    @ ./timing.jl:299 [inlined]
  [3] #_alloc#204
    @ ~/.julia/packages/CUDA/QjuNX/src/pool.jl:304 [inlined]
  [4] #alloc#203
    @ ~/.julia/packages/CUDA/QjuNX/src/pool.jl:290 [inlined]
  [5] alloc
    @ ~/.julia/packages/CUDA/QjuNX/src/pool.jl:286 [inlined]
  [6] CuArray
    @ ~/.julia/packages/CUDA/QjuNX/src/array.jl:42 [inlined]
  [7] CuArray
    @ ~/.julia/packages/CUDA/QjuNX/src/array.jl:125 [inlined]
  [8] CuArray
    @ ~/.julia/packages/CUDA/QjuNX/src/array.jl:132 [inlined]
  [9] with_workspace(f::CUDA.CUDNN.var"#1183#1187"{Vector{CUDA.CUDNN.cudnnConvolutionFwdAlgoPerfStruct}, Vector{Int32}, Int64, CUDA.CUDNN.cudnnTensorDescriptor, CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CUDA.CUDNN.cudnnFilterDescriptor, CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CUDA.CUDNN.cudnnConvolutionDescriptor, CUDA.CUDNN.cudnnTensorDescriptor, CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}}, eltyp::Type{UInt8}, size::CUDA.CUDNN.var"#workspaceSize#1186"{CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}}, fallback::Nothing; keep::Bool)
    @ CUDA.APIUtils ~/.julia/packages/CUDA/QjuNX/lib/utils/call.jl:65
 [10] with_workspace
    @ ~/.julia/packages/CUDA/QjuNX/lib/utils/call.jl:58 [inlined]
 [11] #with_workspace#1
    @ ~/.julia/packages/CUDA/QjuNX/lib/utils/call.jl:53 [inlined]
 [12] with_workspace (repeats 2 times)
    @ ~/.julia/packages/CUDA/QjuNX/lib/utils/call.jl:53 [inlined]
 [13] #1182
    @ ~/.julia/packages/CUDA/QjuNX/lib/cudnn/convolution.jl:181 [inlined]
 [14] get!(default::CUDA.CUDNN.var"#1182#1185"{CUDA.CUDNN.cudnnTensorDescriptor, CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CUDA.CUDNN.cudnnFilterDescriptor, CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CUDA.CUDNN.cudnnConvolutionDescriptor, CUDA.CUDNN.cudnnTensorDescriptor, CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}}, h::Dict{Tuple, CUDA.CUDNN.cudnnConvolutionFwdAlgoPerfStruct}, key::Tuple{CUDA.CUDNN.cudnnTensorDescriptor, CUDA.CUDNN.cudnnFilterDescriptor, CUDA.CUDNN.cudnnConvolutionDescriptor, Nothing, CUDA.CUDNN.cudnnActivationMode_t})
    @ Base ./dict.jl:464
 [15] #1181
    @ ~/.julia/packages/CUDA/QjuNX/lib/cudnn/convolution.jl:176 [inlined]
 [16] lock(f::CUDA.CUDNN.var"#1181#1184"{CUDA.CUDNN.cudnnTensorDescriptor, CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CUDA.CUDNN.cudnnFilterDescriptor, CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CUDA.CUDNN.cudnnConvolutionDescriptor, CUDA.CUDNN.cudnnTensorDescriptor, CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, Nothing, CUDA.CUDNN.cudnnActivationMode_t}, l::ReentrantLock)
    @ Base ./lock.jl:190
 [17] cudnnConvolutionFwdAlgoPerf(xDesc::CUDA.CUDNN.cudnnTensorDescriptor, x::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, wDesc::CUDA.CUDNN.cudnnFilterDescriptor, w::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, convDesc::CUDA.CUDNN.cudnnConvolutionDescriptor, yDesc::CUDA.CUDNN.cudnnTensorDescriptor, y::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, biasDesc::Nothing, activation::CUDA.CUDNN.cudnnActivationMode_t)
    @ CUDA.CUDNN ~/.julia/packages/CUDA/QjuNX/lib/cudnn/convolution.jl:175
 [18] cudnnConvolutionForwardAD(w::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, x::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, bias::Nothing, z::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}; y::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, activation::CUDA.CUDNN.cudnnActivationMode_t, convDesc::CUDA.CUDNN.cudnnConvolutionDescriptor, wDesc::CUDA.CUDNN.cudnnFilterDescriptor, xDesc::CUDA.CUDNN.cudnnTensorDescriptor, yDesc::CUDA.CUDNN.cudnnTensorDescriptor, zDesc::CUDA.CUDNN.cudnnTensorDescriptor, biasDesc::Nothing, alpha::Base.RefValue{Float32}, beta::Base.RefValue{Float32}, dw::Base.RefValue{Any}, dx::Base.RefValue{Any}, dz::Base.RefValue{Any}, dbias::Base.RefValue{Any}, dready::Base.RefValue{Bool})
    @ CUDA.CUDNN ~/.julia/packages/CUDA/QjuNX/lib/cudnn/convolution.jl:102
 [19] #cudnnConvolutionForwardWithDefaults#1175
    @ ~/.julia/packages/CUDA/QjuNX/lib/cudnn/convolution.jl:96 [inlined]
 [20] #cudnnConvolutionForward!#1174
    @ ~/.julia/packages/CUDA/QjuNX/lib/cudnn/convolution.jl:53 [inlined]
 [21] conv!(y::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, x::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, w::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, cdims::DenseConvDims{2, 2, 2, 4, 2}; alpha::Int64, beta::Int64, algo::Int64)
    @ NNlibCUDA ~/.julia/packages/NNlibCUDA/i1IW9/src/cudnn/conv.jl:67
 [22] conv!
    @ ~/.julia/packages/NNlibCUDA/i1IW9/src/cudnn/conv.jl:60 [inlined]
 [23] conv(x::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, w::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, cdims::DenseConvDims{2, 2, 2, 4, 2}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ NNlib ~/.julia/packages/NNlib/TAcqa/src/conv.jl:88
 [24] conv
    @ ~/.julia/packages/NNlib/TAcqa/src/conv.jl:86 [inlined]
 [25] (::Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}})(x::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer})
    @ Flux ~/.julia/packages/Flux/18YZE/src/layers/conv.jl:170
 [26] macro expansion
    @ ~/.julia/packages/Flux/18YZE/src/layers/basic.jl:53 [inlined]
 [27] applychain
    @ ~/.julia/packages/Flux/18YZE/src/layers/basic.jl:53 [inlined]
 [28] Chain
    @ ~/.julia/packages/Flux/18YZE/src/layers/basic.jl:51 [inlined]
 [29] macro expansion
    @ ~/.julia/packages/Flux/18YZE/src/layers/basic.jl:53 [inlined]
 [30] applychain(layers::Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, typeof(Flux.flatten), Dense{typeof(identity), CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}, x::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer})
    @ Flux ~/.julia/packages/Flux/18YZE/src/layers/basic.jl:53
 [31] (::Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, typeof(Flux.flatten), Dense{typeof(identity), CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}})(x::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer})
    @ Flux ~/.julia/packages/Flux/18YZE/src/layers/basic.jl:51
 [32] optimize(actor::Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, Chain{Tuple{Conv{2, 4, typeof(relu), CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}, BatchNorm{typeof(identity), CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, typeof(Flux.flatten), Dense{typeof(identity), CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}}}, n::Int64)
    @ Main ./untitled-567b85fe822168f1f1a1e5b9e8ad37a7:11
 [33] top-level scope
    @ untitled-567b85fe822168f1f1a1e5b9e8ad37a7:25
 [34] eval
    @ ./boot.jl:373 [inlined]
 [35] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1196
in expression starting at untitled-567b85fe822168f1f1a1e5b9e8ad37a7:25
```

**Comment by fabricerosay** [comment]
I did try and thought it failed but the hotfix was not available actually. I've been fooled cause another push was made that caused an update.

**Comment by fabricerosay** [comment]
Proudly google->read Pkg doc->learned how to install a branch and hourra!
It seems to work, at least MWE from above now doesn't oom.

**Comment by maleadt** [comment]
The hotfix isn't on the master branch, it's on a feature branch. See the PR.
